### ISSUE TITLE
8.4.3 ODBC Driver unable to establish the connection

### ISSUE THREAD

**Issue by hemantmalik** [elastic/elasticsearch-sql-odbc#314]
### Environment
Windows Server 2022 Datacenter Azure Edition (21H2)
No Proxy
US Location

### Expected Behaviour
Test Connection successful
### Actual Behaviour
<img width="394" alt="image" src="https://user-images.githubusercontent.com/26748353/197066362-95c604d6-aca8-486f-aaa8-5a892febbcdf.png">

### Steps to reproduce the behavior

1. Install ODBC Driver 
2. Configure DSN
3. Test Connection

DEBUG log file
[esodbc_20221020214711___2608-2.log](https://github.com/elastic/elasticsearch-sql-odbc/files/9834157/esodbc_20221020214711___2608-2.log)

cc: @jeffmaddocks @bpintea

**Comment by bpintea** [comment]
This is caused by the unfortunate delayed introduction of the Version type support to the ODBC driver (see [comment](https://github.com/elastic/elasticsearch-sql-odbc/issues/311#issuecomment-1235718420)). The workaround is to use an older version of the driver. 8.5 will work as expected too (as well as a potential 8.4.4, but this doesn't seem it'll be released).

**Comment by jeffmaddocks** [comment]
Thanks @bpintea, I went thru the drivers back to 8.3.3, which worked. I will work with Hemant to identify the right channel to have our documentation updated.
