### ISSUE TITLE
[Question] How to set local timezone when using connection string?

### ISSUE THREAD

**Issue by UlyssesWu** [elastic/elasticsearch-sql-odbc#325]
``` csharp
var connectionString = "Driver={Elasticsearch Driver};SERVER=XXX;Port=XXX;UID=XXX;PWD=XXX;ApplyTZ=true"
var odbcConn = new OdbcConnection(connectionString);
odbcConn.Open();
```

```
System.Data.Odbc.OdbcException
  HResult=0x80131937
  Message=ERROR [HY000] [Elastic][EsODBC 7.10.2(v7.10.1-1-gb978e90+,u,r) Driver]x_content_parse_exception: [-1:94] [sql/query] failed to parse field [time_zone]
ERROR [HY000] [Elastic][EsODBC 7.10.2(v7.10.1-1-gb978e90+,u,r) Driver]x_content_parse_exception: [-1:94] [sql/query] failed to parse field [time_zone]
[Elastic][EsODBC 7.10.2(v7.10.1-1-gb978e90+,u,r) Driver]x_content_parse_exception: [-1:94] [sql/query] failed to parse field [time_zone]
```

Tried `TimeZone=Asia/Shanghai;` or `TZ=Asia/Shanghai;` no luck.

**Comment by bpintea** [comment]
@UlyssesWu
please use https://discuss.elastic.co/ to post usability questions.

> How to set local timezone when using connection string?

The driver will either use the `TZ` _environment variable_, if one is set, or otherwise that of the system. In order to inspect what value the driver will use, you may [enable logging](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-odbc-setup.html#_2_6_logging_parameters) and inspect the lines. Or open a question on the discuss forum and append the relevant logs -- feel free to leave a comment here with the URL of the issue if so.

But otherwise, the timezone value itself - "Asia/Shanghai" - should work.
