### ISSUE TITLE
Can you use File DSN?

### ISSUE THREAD

**Issue by taku333** [elastic/elasticsearch-sql-odbc#92]
Hi.
I'm setting Elasticsearch SQL ODBC Driver.
At that time I noticed　Can you use File DSN?

The following is written as 「three tabs」.
[Configuration](https://www.elastic.co/guide/en/elasticsearch/sql-odbc/6.5/sql-odbc-setup.html#_2_1_launch_elasticsearch_sql_odbc_driver_dsn_editor)
```
The next step is to configure a DSN. You can choose between the following options mapped on the first three tabs of the Administrator application:
```

However, only「User DSN」and「System DSN」are written in「2.Configure a DSN」.

Thank you for your review.

**Comment by bpintea** [comment]
Kindly note the issue template instructions:

```
** Please read the guidelines below. **

GitHub is reserved for bug reports and feature requests. The best place to
ask a general question is at the Elastic forums: https://discuss.elastic.co/c/elasticsearch
GitHub is not the place for general questions.
```

Since there is indeed an issue with this functionality, I'm going to answer here this one time, but kindly do use the forums for any further general questions.

It is technically possible to use the `File DSN`, but that's not straight-forward. I've opened a ticket to address this issue (https://github.com/elastic/elasticsearch-sql-odbc/issues/95).

Detailed explanation: this is currently only working if pressing on the `Advanced...` button on the window asking to choose the driver:
![advanced](https://user-images.githubusercontent.com/1562801/51523474-02730f00-1e2c-11e9-8b19-e69fc35eaff4.png)
Then, one would need to provide in the "Type driver-specific keywords and values:" text box the connection string parameters and their values and *most importantly*, untick the `Verify this connection (recommended)`. The connection parameter names are not documented, but they could be read from the Registry if a User/System DSN has been already created.

**Comment by taku333** [comment]
>Since there is indeed an issue with this functionality, I'm going to answer here this one time, but kindly do use the forums for any further general questions.
→Soory.

>It is technically possible to use the File DSN, but that's not straight-forward. I've opened a ticket to address this issue (#95).
→Thanks writing.
